import type { Metadata } from "next";
import { Geist, Geist_Mono,ABeeZee } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import Header from "@/components/header";
import Link from "next/link";

const abeezee = ABeeZee(
  {subsets:["latin"],weight:'400'}
)


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={abeezee.className}>
        <AntdRegistry>
          <div className="container mx-auto">
            <div className="flex justify-center text-blue-500 p-6 gap-6">
              <Link href="/">Home</Link>
              <Link href="/visiters">visiters</Link>
            </div>
            <div className="flex gap-6">
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
